### ISSUE TITLE
Optimised vendor libraries

### ISSUE THREAD

**Issue by bkazi** [GoogleChromeLabs/samples-module-loading-comparison#1]
This is a really useful benchmark, just what I was looking for!

I was wondering if there would be a difference if bundled, optimised vendor bundles were used along with unbundled app modules.
Something like ReactHN using react.min.js but it's own scripts unbundled
Would load times improve enough to be as good as bundled or at least good enough to the point where the gains in caching might be a decent tradeoff for larger load times?

**Comment by sgomes** [comment]
Hey @bkazi, thank you! Sorry for the late reply, only saw this now.

As part of the build process, this does do minification for both the bundled and unbundled versions. This is not the same minification that the original projects did, I'm sure, but I needed something consistent across all three versions.

In any case, the numbers you get from the bundled versions that this produces should be similar to if you were to use the original `foo.min.js`.

Hope this helps!
