### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by fsx950223** [GoogleChromeLabs/samples-module-loading-comparison#3]
![image](https://user-images.githubusercontent.com/17592563/30549860-7a0e8cce-9cc8-11e7-994c-1cc144207fa5.png)
![image](https://user-images.githubusercontent.com/17592563/30549884-89286144-9cc8-11e7-8f3b-5e587f8af6b4.png)
Chrome throw a error when I use mdc which is installed by npm and I have to specific directory/index.js when I import js files

**Comment by sgomes** [comment]
This problem is completely unrelated to this project. Please file an issue on the Material Components for the web repo at https://github.com/material-components/material-components-web
